import Head from 'next/head'


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Redux Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1> Refux next app</h1>
      </main>

      
    </div>
  )
}
