import Head from 'next/head'
import PostsList from '../components/PostsList'
import AddPostForm from '../components/AddPostForm'


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Redux Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container max-w-[700px] mx-auto bg-gray-800 text-whites h-screen p-10 pt-10'>
      <AddPostForm />
        <PostsList />
        
      </main>

      
    </div>
  )
}
